icons = "awesome"

[theme]
name = "slick"
[theme.overrides]
alternating_tint_bg = "#1e1e1e"
idle_bg = "#52133C"

[[block]]
block = "weather"
format = "{weather} {temp}ยบ"
service = {name = "openweathermap", api_key = "XXXXXXX", city_id = "XXXXXXX", units = "metric"}
interval = 60

[[block]]
block = "net"
device = "wlp7s0"
ssid = false
signal_strength = false
ip = false
speed_up = true
speed_down = true
interval = 5
use_bits = true

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mum}MB"
warning_mem = 80
critical_mem = 95
interval = 5

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "sound"

[[block]]
block = "battery"
format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"